#ifndef PROJ_ANDROID_STUDIO_ANDROIDCAMERAFRAMECONVERTER_H
#define PROJ_ANDROID_STUDIO_ANDROIDCAMERAFRAMECONVERTER_H

#include "cocos2d.h"

class AndroidCameraFrameConverter {
};


#endif //PROJ_ANDROID_STUDIO_ANDROIDCAMERAFRAMECONVERTER_H
